# Generated by Django 3.2.8 on 2025-07-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30, null=True, verbose_name='Nombre(s)')),
            ],
        ),
    ]
