# Generated by Django 3.2.8 on 2025-07-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apneasueno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cansado',
            field=models.BooleanField(null=True, verbose_name='¿Se siente con frecuencia cansado, fatigado o somnoliento durante el dia? (por ejemplo, se queda dormido mientras conduce o habla con alguien)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cuello',
            field=models.FloatField(null=True, verbose_name='Circunferencia del cuello (cm)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estatura',
            field=models.FloatField(null=True, verbose_name='Estatura (m)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='imc',
            field=models.FloatField(editable=False, null=True, verbose_name='Índice de Masa Corporal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre(s)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observado',
            field=models.BooleanField(null=True, verbose_name='¿Alguien lo observó dejar de respirar o ahogarse/quedarse sin aliento mientras dormía?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='presion_alta',
            field=models.BooleanField(null=True, verbose_name='¿Tiene o está recibiendo tratamiento para pressión arterial alta?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='puntuacion_stopbang',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Puntuación STOP-BANG'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='riesgo',
            field=models.CharField(editable=False, max_length=20, null=True, verbose_name='Nivel de riesgo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ronca',
            field=models.BooleanField(null=True, verbose_name='¿Ronca fuerte? (Tan fuerte que se escucha a través de puertas cerradas o su pareja lo codea por roncar de noche)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID o Número de Expediente'),
        ),
    ]
